# Generated by Django 5.0.10 on 2024-12-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
        migrations.AlterModelTable(
            name='customers',
            table='Customers',
        ),
    ]
